/******************************************************************************
** <auto-generated>
**     This code was generated by a tool.
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>
**
** Copyright (c) 2006-2018 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.7
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.7, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET based OPC UA Client Server SDK
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.7/
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace yourorganisation.BA
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class DataTypes
    {
    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class Methods
    {
        /// <summary>
        /// The identifier for the Start Method.
        /// </summary>
        public const uint ControllerType_Start = 7001;

        /// <summary>
        /// The identifier for the Stop Method.
        /// </summary>
        public const uint ControllerType_Stop = 7002;

        /// <summary>
        /// The identifier for the StartWithSetPoint Method.
        /// </summary>
        public const uint AirConditionerControllerType_StartWithSetPoint = 7003;

    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class Objects
    {
    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class ObjectTypes
    {
        /// <summary>
        /// The identifier for the ControllerType ObjectType.
        /// </summary>
        public const uint ControllerType = 1001;

        /// <summary>
        /// The identifier for the FurnaceControllerType ObjectType.
        /// </summary>
        public const uint FurnaceControllerType = 1002;

        /// <summary>
        /// The identifier for the AirConditionerControllerType ObjectType.
        /// </summary>
        public const uint AirConditionerControllerType = 1003;

        /// <summary>
        /// The identifier for the ControllerEventType ObjectType.
        /// </summary>
        public const uint ControllerEventType = 1004;

    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the State Variable.
        /// </summary>
        public const uint ControllerType_State = 6001;

        /// <summary>
        /// The identifier for the Temperature Variable.
        /// </summary>
        public const uint ControllerType_Temperature = 6002;

        /// <summary>
        /// The identifier for the TemperatureSetPoint Variable.
        /// </summary>
        public const uint ControllerType_TemperatureSetPoint = 6003;

        /// <summary>
        /// The identifier for the PowerConsumption Variable.
        /// </summary>
        public const uint ControllerType_PowerConsumption = 6004;

        /// <summary>
        /// The identifier for the EURange Variable.
        /// </summary>
        public const uint ControllerType_Temperature_EURange = 6005;

        /// <summary>
        /// The identifier for the EURange Variable.
        /// </summary>
        public const uint ControllerType_TemperatureSetPoint_EURange = 6006;

        /// <summary>
        /// The identifier for the GasFlow Variable.
        /// </summary>
        public const uint FurnaceControllerType_GasFlow = 6007;

        /// <summary>
        /// The identifier for the Humidity Variable.
        /// </summary>
        public const uint AirConditionerControllerType_Humidity = 6008;

        /// <summary>
        /// The identifier for the InputArguments Variable.
        /// </summary>
        public const uint AirConditionerControllerType_StartWithSetPoint_InputArguments = 6009;

        /// <summary>
        /// The identifier for the HumiditySetPoint Variable.
        /// </summary>
        public const uint AirConditionerControllerType_HumiditySetPoint = 6010;

        /// <summary>
        /// The identifier for the Temperature Variable.
        /// </summary>
        public const uint ControllerEventType_Temperature = 6011;

        /// <summary>
        /// The identifier for the State Variable.
        /// </summary>
        public const uint ControllerEventType_State = 6012;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class DataTypeIds
    {
    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class MethodIds
    {
        /// <summary>
        /// The identifier for the ControllerType_Start Method.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_Start = new ExpandedNodeId(Methods.ControllerType_Start, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerType_Stop Method.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_Stop = new ExpandedNodeId(Methods.ControllerType_Stop, Namespaces.BA);

        /// <summary>
        /// The identifier for the AirConditionerControllerType_StartWithSetPoint Method.
        /// </summary>

        public static readonly ExpandedNodeId AirConditionerControllerType_StartWithSetPoint = new ExpandedNodeId(Methods.AirConditionerControllerType_StartWithSetPoint, Namespaces.BA);

    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class ObjectIds
    {
    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class ObjectTypeIds
    {
        /// <summary>
        /// The identifier for the ControllerType ObjectType.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType = new ExpandedNodeId(ObjectTypes.ControllerType, Namespaces.BA);

        /// <summary>
        /// The identifier for the FurnaceControllerType ObjectType.
        /// </summary>

        public static readonly ExpandedNodeId FurnaceControllerType = new ExpandedNodeId(ObjectTypes.FurnaceControllerType, Namespaces.BA);

        /// <summary>
        /// The identifier for the AirConditionerControllerType ObjectType.
        /// </summary>

        public static readonly ExpandedNodeId AirConditionerControllerType = new ExpandedNodeId(ObjectTypes.AirConditionerControllerType, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerEventType ObjectType.
        /// </summary>

        public static readonly ExpandedNodeId ControllerEventType = new ExpandedNodeId(ObjectTypes.ControllerEventType, Namespaces.BA);

    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTypes in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the ControllerType_State Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_State = new ExpandedNodeId(Variables.ControllerType_State, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerType_Temperature Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_Temperature = new ExpandedNodeId(Variables.ControllerType_Temperature, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerType_TemperatureSetPoint Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_TemperatureSetPoint = new ExpandedNodeId(Variables.ControllerType_TemperatureSetPoint, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerType_PowerConsumption Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_PowerConsumption = new ExpandedNodeId(Variables.ControllerType_PowerConsumption, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerType_Temperature_EURange Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_Temperature_EURange = new ExpandedNodeId(Variables.ControllerType_Temperature_EURange, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerType_TemperatureSetPoint_EURange Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerType_TemperatureSetPoint_EURange = new ExpandedNodeId(Variables.ControllerType_TemperatureSetPoint_EURange, Namespaces.BA);

        /// <summary>
        /// The identifier for the FurnaceControllerType_GasFlow Variable.
        /// </summary>

        public static readonly ExpandedNodeId FurnaceControllerType_GasFlow = new ExpandedNodeId(Variables.FurnaceControllerType_GasFlow, Namespaces.BA);

        /// <summary>
        /// The identifier for the AirConditionerControllerType_Humidity Variable.
        /// </summary>

        public static readonly ExpandedNodeId AirConditionerControllerType_Humidity = new ExpandedNodeId(Variables.AirConditionerControllerType_Humidity, Namespaces.BA);

        /// <summary>
        /// The identifier for the AirConditionerControllerType_StartWithSetPoint_InputArguments Variable.
        /// </summary>

        public static readonly ExpandedNodeId AirConditionerControllerType_StartWithSetPoint_InputArguments = new ExpandedNodeId(Variables.AirConditionerControllerType_StartWithSetPoint_InputArguments, Namespaces.BA);

        /// <summary>
        /// The identifier for the AirConditionerControllerType_HumiditySetPoint Variable.
        /// </summary>

        public static readonly ExpandedNodeId AirConditionerControllerType_HumiditySetPoint = new ExpandedNodeId(Variables.AirConditionerControllerType_HumiditySetPoint, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerEventType_Temperature Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerEventType_Temperature = new ExpandedNodeId(Variables.ControllerEventType_Temperature, Namespaces.BA);

        /// <summary>
        /// The identifier for the ControllerEventType_State Variable.
        /// </summary>

        public static readonly ExpandedNodeId ControllerEventType_State = new ExpandedNodeId(Variables.ControllerEventType_State, Namespaces.BA);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares constants for all VariableType in the Model Design.
    /// </summary>
    /// <exclude />
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.2.1")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model Design.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the AirConditionerControllerType component.
        /// </summary>
        public const string AirConditionerControllerType = "AirConditionerControllerType";

        /// <summary>
        /// The BrowseName for the ControllerEventType component.
        /// </summary>
        public const string ControllerEventType = "ControllerEventType";

        /// <summary>
        /// The BrowseName for the ControllerType component.
        /// </summary>
        public const string ControllerType = "ControllerType";

        /// <summary>
        /// The BrowseName for the FurnaceControllerType component.
        /// </summary>
        public const string FurnaceControllerType = "FurnaceControllerType";

        /// <summary>
        /// The BrowseName for the GasFlow component.
        /// </summary>
        public const string GasFlow = "GasFlow";

        /// <summary>
        /// The BrowseName for the Humidity component.
        /// </summary>
        public const string Humidity = "Humidity";

        /// <summary>
        /// The BrowseName for the HumiditySetPoint component.
        /// </summary>
        public const string HumiditySetPoint = "HumiditySetPoint";

        /// <summary>
        /// The BrowseName for the PowerConsumption component.
        /// </summary>
        public const string PowerConsumption = "PowerConsumption";

        /// <summary>
        /// The BrowseName for the Start component.
        /// </summary>
        public const string Start = "Start";

        /// <summary>
        /// The BrowseName for the StartWithSetPoint component.
        /// </summary>
        public const string StartWithSetPoint = "StartWithSetPoint";

        /// <summary>
        /// The BrowseName for the State component.
        /// </summary>
        public const string State = "State";

        /// <summary>
        /// The BrowseName for the Stop component.
        /// </summary>
        public const string Stop = "Stop";

        /// <summary>
        /// The BrowseName for the Temperature component.
        /// </summary>
        public const string Temperature = "Temperature";

        /// <summary>
        /// The BrowseName for the TemperatureSetPoint component.
        /// </summary>
        public const string TemperatureSetPoint = "TemperatureSetPoint";

    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the model design.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the BA namespace.
        /// </summary>
        public const string BA = "http://yourorganisation.org/BuildingAutomation/";
    }
    #endregion
}
