//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ConsoleApplication2.Aries {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InboundSoap", Namespace="http://Libra.com/Aries")]
    public partial class Inbound : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GoodsReceiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GoodsTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback AriesBackFlushOperationCompleted;
        
        private System.Threading.SendOrPostCallback InnerGoodsTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback PickingListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Inbound() {
            this.Url = global::ConsoleApplication2.Properties.Settings.Default.ConsoleApplication2_Aries_Inbound;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GoodsReceiveCompletedEventHandler GoodsReceiveCompleted;
        
        /// <remarks/>
        public event GoodsTransferCompletedEventHandler GoodsTransferCompleted;
        
        /// <remarks/>
        public event AriesBackFlushCompletedEventHandler AriesBackFlushCompleted;
        
        /// <remarks/>
        public event InnerGoodsTransferCompletedEventHandler InnerGoodsTransferCompleted;
        
        /// <remarks/>
        public event CloseOrderCompletedEventHandler CloseOrderCompleted;
        
        /// <remarks/>
        public event PickingListCompletedEventHandler PickingListCompleted;
        
        /// <remarks/>
        public event CycleCountCompletedEventHandler CycleCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/GoodsReceive", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage GoodsReceive(GoodsReceiveInfo[] orderAsnInfo) {
            object[] results = this.Invoke("GoodsReceive", new object[] {
                        orderAsnInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void GoodsReceiveAsync(GoodsReceiveInfo[] orderAsnInfo) {
            this.GoodsReceiveAsync(orderAsnInfo, null);
        }
        
        /// <remarks/>
        public void GoodsReceiveAsync(GoodsReceiveInfo[] orderAsnInfo, object userState) {
            if ((this.GoodsReceiveOperationCompleted == null)) {
                this.GoodsReceiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoodsReceiveOperationCompleted);
            }
            this.InvokeAsync("GoodsReceive", new object[] {
                        orderAsnInfo}, this.GoodsReceiveOperationCompleted, userState);
        }
        
        private void OnGoodsReceiveOperationCompleted(object arg) {
            if ((this.GoodsReceiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoodsReceiveCompleted(this, new GoodsReceiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/GoodsTransfer", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage GoodsTransfer(TransferInfo transferInfo) {
            object[] results = this.Invoke("GoodsTransfer", new object[] {
                        transferInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void GoodsTransferAsync(TransferInfo transferInfo) {
            this.GoodsTransferAsync(transferInfo, null);
        }
        
        /// <remarks/>
        public void GoodsTransferAsync(TransferInfo transferInfo, object userState) {
            if ((this.GoodsTransferOperationCompleted == null)) {
                this.GoodsTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoodsTransferOperationCompleted);
            }
            this.InvokeAsync("GoodsTransfer", new object[] {
                        transferInfo}, this.GoodsTransferOperationCompleted, userState);
        }
        
        private void OnGoodsTransferOperationCompleted(object arg) {
            if ((this.GoodsTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoodsTransferCompleted(this, new GoodsTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/AriesBackFlush", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage AriesBackFlush(BackFlushInfo backFlashInfo) {
            object[] results = this.Invoke("AriesBackFlush", new object[] {
                        backFlashInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void AriesBackFlushAsync(BackFlushInfo backFlashInfo) {
            this.AriesBackFlushAsync(backFlashInfo, null);
        }
        
        /// <remarks/>
        public void AriesBackFlushAsync(BackFlushInfo backFlashInfo, object userState) {
            if ((this.AriesBackFlushOperationCompleted == null)) {
                this.AriesBackFlushOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAriesBackFlushOperationCompleted);
            }
            this.InvokeAsync("AriesBackFlush", new object[] {
                        backFlashInfo}, this.AriesBackFlushOperationCompleted, userState);
        }
        
        private void OnAriesBackFlushOperationCompleted(object arg) {
            if ((this.AriesBackFlushCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AriesBackFlushCompleted(this, new AriesBackFlushCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/InnerGoodsTransfer", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage InnerGoodsTransfer(InnerTransferInfo[] innerGoodsReceiveInfo) {
            object[] results = this.Invoke("InnerGoodsTransfer", new object[] {
                        innerGoodsReceiveInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void InnerGoodsTransferAsync(InnerTransferInfo[] innerGoodsReceiveInfo) {
            this.InnerGoodsTransferAsync(innerGoodsReceiveInfo, null);
        }
        
        /// <remarks/>
        public void InnerGoodsTransferAsync(InnerTransferInfo[] innerGoodsReceiveInfo, object userState) {
            if ((this.InnerGoodsTransferOperationCompleted == null)) {
                this.InnerGoodsTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInnerGoodsTransferOperationCompleted);
            }
            this.InvokeAsync("InnerGoodsTransfer", new object[] {
                        innerGoodsReceiveInfo}, this.InnerGoodsTransferOperationCompleted, userState);
        }
        
        private void OnInnerGoodsTransferOperationCompleted(object arg) {
            if ((this.InnerGoodsTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InnerGoodsTransferCompleted(this, new InnerGoodsTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/CloseOrder", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage CloseOrder(CloseOrderInfo closeOrderInfo) {
            object[] results = this.Invoke("CloseOrder", new object[] {
                        closeOrderInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void CloseOrderAsync(CloseOrderInfo closeOrderInfo) {
            this.CloseOrderAsync(closeOrderInfo, null);
        }
        
        /// <remarks/>
        public void CloseOrderAsync(CloseOrderInfo closeOrderInfo, object userState) {
            if ((this.CloseOrderOperationCompleted == null)) {
                this.CloseOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseOrderOperationCompleted);
            }
            this.InvokeAsync("CloseOrder", new object[] {
                        closeOrderInfo}, this.CloseOrderOperationCompleted, userState);
        }
        
        private void OnCloseOrderOperationCompleted(object arg) {
            if ((this.CloseOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseOrderCompleted(this, new CloseOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/PickingList", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage PickingList(PickingListInfo[] pickingListInfo) {
            object[] results = this.Invoke("PickingList", new object[] {
                        pickingListInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void PickingListAsync(PickingListInfo[] pickingListInfo) {
            this.PickingListAsync(pickingListInfo, null);
        }
        
        /// <remarks/>
        public void PickingListAsync(PickingListInfo[] pickingListInfo, object userState) {
            if ((this.PickingListOperationCompleted == null)) {
                this.PickingListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPickingListOperationCompleted);
            }
            this.InvokeAsync("PickingList", new object[] {
                        pickingListInfo}, this.PickingListOperationCompleted, userState);
        }
        
        private void OnPickingListOperationCompleted(object arg) {
            if ((this.PickingListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PickingListCompleted(this, new PickingListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Libra.com/Aries/CycleCount", RequestNamespace="http://Libra.com/Aries", ResponseNamespace="http://Libra.com/Aries", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InvokeResultMessage CycleCount(CycleCountInfo cycleCountInfo) {
            object[] results = this.Invoke("CycleCount", new object[] {
                        cycleCountInfo});
            return ((InvokeResultMessage)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCountAsync(CycleCountInfo cycleCountInfo) {
            this.CycleCountAsync(cycleCountInfo, null);
        }
        
        /// <remarks/>
        public void CycleCountAsync(CycleCountInfo cycleCountInfo, object userState) {
            if ((this.CycleCountOperationCompleted == null)) {
                this.CycleCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCountOperationCompleted);
            }
            this.InvokeAsync("CycleCount", new object[] {
                        cycleCountInfo}, this.CycleCountOperationCompleted, userState);
        }
        
        private void OnCycleCountOperationCompleted(object arg) {
            if ((this.CycleCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCountCompleted(this, new CycleCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class GoodsReceiveInfo {
        
        private string siteField;
        
        private string recLocField;
        
        private string orderNoField;
        
        private string detailNoField;
        
        private string shipFromField;
        
        private string partNoField;
        
        private decimal rcptQtyField;
        
        private string uomField;
        
        private string effectiveDateField;
        
        private string syncFlagIDField;
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string RecLoc {
            get {
                return this.recLocField;
            }
            set {
                this.recLocField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string DetailNo {
            get {
                return this.detailNoField;
            }
            set {
                this.detailNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFrom {
            get {
                return this.shipFromField;
            }
            set {
                this.shipFromField = value;
            }
        }
        
        /// <remarks/>
        public string PartNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal RcptQty {
            get {
                return this.rcptQtyField;
            }
            set {
                this.rcptQtyField = value;
            }
        }
        
        /// <remarks/>
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        public string EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string SyncFlagID {
            get {
                return this.syncFlagIDField;
            }
            set {
                this.syncFlagIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class CycleCountInfo {
        
        private string fromSiteField;
        
        private string toSiteField;
        
        private string orderNoField;
        
        private string orderTypeField;
        
        private string fromLocField;
        
        private string toLocField;
        
        private string partNoField;
        
        private decimal qtyField;
        
        private decimal stockQtyField;
        
        private System.DateTime effDateField;
        
        private string syncFlagIDField;
        
        /// <remarks/>
        public string FromSite {
            get {
                return this.fromSiteField;
            }
            set {
                this.fromSiteField = value;
            }
        }
        
        /// <remarks/>
        public string ToSite {
            get {
                return this.toSiteField;
            }
            set {
                this.toSiteField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FromLoc {
            get {
                return this.fromLocField;
            }
            set {
                this.fromLocField = value;
            }
        }
        
        /// <remarks/>
        public string ToLoc {
            get {
                return this.toLocField;
            }
            set {
                this.toLocField = value;
            }
        }
        
        /// <remarks/>
        public string PartNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal StockQty {
            get {
                return this.stockQtyField;
            }
            set {
                this.stockQtyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EffDate {
            get {
                return this.effDateField;
            }
            set {
                this.effDateField = value;
            }
        }
        
        /// <remarks/>
        public string SyncFlagID {
            get {
                return this.syncFlagIDField;
            }
            set {
                this.syncFlagIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class PickingListInfo {
        
        private string siteField;
        
        private string bomCodeField;
        
        private decimal qtyField;
        
        private string productLineField;
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string BomCode {
            get {
                return this.bomCodeField;
            }
            set {
                this.bomCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string ProductLine {
            get {
                return this.productLineField;
            }
            set {
                this.productLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class CloseOrderInfo {
        
        private string siteField;
        
        private string orderCodeField;
        
        private string orderStatusField;
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string OrderCode {
            get {
                return this.orderCodeField;
            }
            set {
                this.orderCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class InnerTransferInfo {
        
        private string transferIDField;
        
        private string siteField;
        
        private string orderNoField;
        
        private string orderTypeField;
        
        private string fromLocField;
        
        private string toLocField;
        
        private System.DateTime effDTField;
        
        private string commentsField;
        
        private string partNoField;
        
        private string uOMField;
        
        private decimal qtyField;
        
        private string syncFlagIDField;
        
        /// <remarks/>
        public string TransferID {
            get {
                return this.transferIDField;
            }
            set {
                this.transferIDField = value;
            }
        }
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FromLoc {
            get {
                return this.fromLocField;
            }
            set {
                this.fromLocField = value;
            }
        }
        
        /// <remarks/>
        public string ToLoc {
            get {
                return this.toLocField;
            }
            set {
                this.toLocField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EffDT {
            get {
                return this.effDTField;
            }
            set {
                this.effDTField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string PartNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string SyncFlagID {
            get {
                return this.syncFlagIDField;
            }
            set {
                this.syncFlagIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class BackFlushInfo {
        
        private string partNoField;
        
        private string bomCodeField;
        
        private string routingCodeField;
        
        private string qTYField;
        
        private string siteField;
        
        private string productionLineField;
        
        private string effictiveDateField;
        
        private string employeeField;
        
        private string operationField;
        
        private string shiftField;
        
        private string modIssrcField;
        
        private string syncFlagIDField;
        
        /// <remarks/>
        public string PartNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        public string BomCode {
            get {
                return this.bomCodeField;
            }
            set {
                this.bomCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RoutingCode {
            get {
                return this.routingCodeField;
            }
            set {
                this.routingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string ProductionLine {
            get {
                return this.productionLineField;
            }
            set {
                this.productionLineField = value;
            }
        }
        
        /// <remarks/>
        public string EffictiveDate {
            get {
                return this.effictiveDateField;
            }
            set {
                this.effictiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        public string Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        public string Shift {
            get {
                return this.shiftField;
            }
            set {
                this.shiftField = value;
            }
        }
        
        /// <remarks/>
        public string ModIssrc {
            get {
                return this.modIssrcField;
            }
            set {
                this.modIssrcField = value;
            }
        }
        
        /// <remarks/>
        public string SyncFlagID {
            get {
                return this.syncFlagIDField;
            }
            set {
                this.syncFlagIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class TransferInfo {
        
        private string transferIDField;
        
        private string fromSiteField;
        
        private string toSiteField;
        
        private string orderNoField;
        
        private string orderTypeField;
        
        private string fromLocField;
        
        private string toLocField;
        
        private string partNoField;
        
        private decimal qtyField;
        
        private System.DateTime effDTField;
        
        private string commentsField;
        
        private string syncFlagIDField;
        
        /// <remarks/>
        public string TransferID {
            get {
                return this.transferIDField;
            }
            set {
                this.transferIDField = value;
            }
        }
        
        /// <remarks/>
        public string FromSite {
            get {
                return this.fromSiteField;
            }
            set {
                this.fromSiteField = value;
            }
        }
        
        /// <remarks/>
        public string ToSite {
            get {
                return this.toSiteField;
            }
            set {
                this.toSiteField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FromLoc {
            get {
                return this.fromLocField;
            }
            set {
                this.fromLocField = value;
            }
        }
        
        /// <remarks/>
        public string ToLoc {
            get {
                return this.toLocField;
            }
            set {
                this.toLocField = value;
            }
        }
        
        /// <remarks/>
        public string PartNo {
            get {
                return this.partNoField;
            }
            set {
                this.partNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EffDT {
            get {
                return this.effDTField;
            }
            set {
                this.effDTField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string SyncFlagID {
            get {
                return this.syncFlagIDField;
            }
            set {
                this.syncFlagIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public partial class InvokeResultMessage {
        
        private RESULTSUMMARY sUMMARYField;
        
        private string mESSAGEField;
        
        private string xMLSCHEMAField;
        
        /// <remarks/>
        public RESULTSUMMARY SUMMARY {
            get {
                return this.sUMMARYField;
            }
            set {
                this.sUMMARYField = value;
            }
        }
        
        /// <remarks/>
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        public string XMLSCHEMA {
            get {
                return this.xMLSCHEMAField;
            }
            set {
                this.xMLSCHEMAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Libra.com/Aries")]
    public enum RESULTSUMMARY {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        FAIL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GoodsReceiveCompletedEventHandler(object sender, GoodsReceiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoodsReceiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoodsReceiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GoodsTransferCompletedEventHandler(object sender, GoodsTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoodsTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoodsTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AriesBackFlushCompletedEventHandler(object sender, AriesBackFlushCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AriesBackFlushCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AriesBackFlushCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InnerGoodsTransferCompletedEventHandler(object sender, InnerGoodsTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InnerGoodsTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InnerGoodsTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CloseOrderCompletedEventHandler(object sender, CloseOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PickingListCompletedEventHandler(object sender, PickingListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PickingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PickingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CycleCountCompletedEventHandler(object sender, CycleCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvokeResultMessage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvokeResultMessage)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591